create database board default character set utf8;

create user 'jspexam'@'localhost' identified by 12345;
create user 'jspexam'@'%' identified by 12345;
GRANT ALL PRIVILEGES ON *.* TO 'jspexam'@'localhost';
GRANT ALL PRIVILEGES ON *.* TO 'jspexam'@'%'

CREATE TABLE BOARD_MEMBER(
	MEMBER_ID	VARCHAR(15),
	MEMBER_PW	VARCHAR(13),
	MEMBER_NAME	VARCHAR(15),
	MEMBER_AGE	INT,
	MEMBER_GENDER	VARCHAR(5),
	MEMBER_EMAIL	VARCHAR(30),
	PRIMARY KEY(MEMBER_ID)
);

CREATE TABLE BOARD(
	BOARD_NUM INT,
	BOARD_NAME VARCHAR(20) NOT NULL,
	BOARD_PASS VARCHAR(15) NOT NULL,
	BOARD_SUBJECT VARCHAR(50) NOT NULL,
	BOARD_CONTENT VARCHAR(2000) NOT NULL,
	BOARD_FILE VARCHAR(50) NOT NULL,
	BOARD_RE_REF INT NOT NULL,
	BOARD_RE_LEV INT NOT NULL,
	BOARD_RE_SEQ INT NOT NULL,
	BOARD_READCOUNT INT DEFAULT 0,
	BOARD_DATE DATE,
	PRIMARY KEY(BOARD_NUM)
);
